version: '2'
services:
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    restart: unless-stopped

  tally_app:
    build: .
    command: ["python", "tallies.py"]
    depends_on:
      - redis
    ports:
      - 5000:5000
    restart: unless-stopped