version: '2'
services:
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    restart: unless-stopped

  tally_http:
    build: .
    depends_on:
      - redis
    ports:
      - 5001:5001
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      PGPASSWORD: app # NOTE: this is a default. DO NOT EVER USE THIS OUTSIDE dev
      ENV: development
    env_file: "secrets.txt"

  tally_queue_consumer:
    build: .
    depends_on:
      - redis
    volumes:
      - ./:/app
    restart: unless-stopped
    env_file: "secrets.txt"
    command: python -u -m skill_handlers.tally_queue_consumer skill_handlers/tally_queue_consumer.py

  database:
    container_name: tally_database_host
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    # TODO: persist pg data in a docker volume
    volumes:
      - ./utilities/pg_init:/docker-entrypoint-initdb.d
