version: '2'
services:
  redis:
    image: redis:alpine
    # TODO: I got this wrong. Use a docker volume here
    volumes:
      - ./data:/data
    restart: unless-stopped

  tally_http:
    build: .
    depends_on:
      - redis
    ports:
      - 5001:5001
    volumes:
      - ./:/app
    restart: unless-stopped
    env_file: "secrets.txt"

  tally_queue_consumer:
    build: .
    depends_on:
      - redis
    volumes:
      - ./:/app
    restart: unless-stopped
    env_file: "secrets.txt"
    command: python -u -m skill_handlers.tally_queue_consumer skill_handlers/tally_queue_consumer.py
